- Dockerfile
- README.md
- docker-compose.yml
- entrypoint.sh
This supports production builds and local development.
> Add Dockerfile and docker-compose config

- themes/wdfn_theme/layouts/_default/single.html
- themes/wdfn_theme/layouts/partials/header.html
since it doesn't exist anymore
> drop google plus

- content/wdfn-faq.md
- content/wdfn-feedback.md
- content/wdfn-tng.md
> correct authorship attribution

- content/wdfn-first look at feedback
@jkreft-usgs please take a look at this draft blog and merge if it looks ok.
> Create wdfn-first look at feedback

- content/wdfn-first_look_at_feedback.md
Updating date and removing draft:True. @jkreft-usgs please push to production when you can.
> un-drafting the blog

- content/release-notes-2019-11-13.md
Content approved by Emily Read
> fix image links

- .gitignore
- Dockerfile
- LICENSE.md
- code.json
- config.toml
- themes/wdfn_theme/package-lock.json
- themes/wdfn_theme/package.json
- themes/wdfn_theme/rollup.config.js
- themes/wdfn_theme/src/scripts/index.js
Also added required LICENSE.md and code.json
> Update deps 1220

- content/pivot.Rmd
- content/pivot.md
Finally got the new version of Hugo installed on my computer, so I can run locally. The figure shortcut was tricky, I didn't realize you needed the curly brackets.
> Image via "figure"

- content/pivot.Rmd
- content/pivot.md
> Looks good locally

- content/pivot.Rmd
- content/pivot.md
@jkreft-usgs or @mbucknell This post was approved by Emily and originally peer reviewed by Sam (in Sharepoint). So, I'll let one of you 2 merge this PR since I took the `draft: true` off.
> Getting name up and removing draft

- content/cloud_data.md
@jkreft-usgs  or @mbucknell - could you merge this?
> updated date, fixed figure address

- content/nldi_update.Rmd
- content/nldi_update.md
> figure fixes.

- content/nldi_update.Rmd
- content/nldi_update.md
Sorry for the line endings issue -- switching between windows and linux is trying.
> reconile supervisory review and draft False

- content/nldi_geoconnex.md
Hoping to track peer review of this draft here.
> PR for peer review

- content/nldi_geoconnex.md
> updates per review

- content/tutorial.Rmd
- content/tutorial.md
(this can be pushed out on the next blog post submission! no rush)
> Forgot to populate author field

- content/WMA-cluster-hire-2021.md
After review and minor edits. All set to go here
> first publish version 

- content/build-river-conditions.md
- themes/wdfn_theme/layouts/shortcodes/rawhtml.html
@collnell provided a wonderful review and I have made lots of edits! Need this to get merged (I don't have write access), so that I can push this through one more review and then will be ready.
I was also able to figure out how to add a video from this repo to my post (thanks @mbucknell!). That was done in https://github.com/usgs/wdfn-blog/commit/1d317ec1ec7aac43a3ebc7b629de6c5520249f1a
> Edits to recreate river conditions following cnell review

- content/build-river-conditions.md
This blog has now been reviewed by Colleen Nell & approved by Jordan Read. Submitting this PR (but keeping as draft) until we are ready to publish along with social media outreach (likely next week).
> Recreate river conditions -- ready to publish

- content/nldi_geoconnex.md
@jkreft-usgs was cc'd on the approval for this. Do you need anything else, Jim?
> take nldi_geoconnex out of draft

- content/30daychartchallenge-2021.md
I've added some text content and updated the header. I felt that the tweets themselves carry the story and not much else was needed, but open to feedback. 
I'm also unsure if a screen reader will pick up the alt text from the tweets themselves, or if that needs to be added. I was not able to find more information about this, and it did not accept adding an `alt="alt caption"` within the `< tweet >` notation like images.
> add to chart challenge post

- content/30daychartchallenge-2021.md
> ready to publish

- content/web-flags.md
> fix cover image

- content/web-flags.md
Made Seasonal a header and bolded important text.
> Fixed minor styling errors

- content/gage_height.md
One of the captions was incomplete and got past us in publishing @jkreft-usgs or @chopkins-usgs if you're around could you complete this?
> Fixed a caption error

- content/Advert_Oct2021_Public_Webinar.md
@nicolefelts  I think these are the changes from your fork.
> make updates to content

- content/batsgw.md
Trying to fix erroneous caption by removing hyperlink
> Fixing image

- content/batsgw.md
Removed the line feeds from captions
> Fixing image captions

- .gitignore
- README.md
> Doc updates for local Windows dev environment

- content/WQP_NewUI.md
> Fixed header

- content/WQP_NewUI.md
> Fixed image tags

- content/WMA-LASD-director-2022.md
This is ready to be pushed to prod, approved by Gary Rowe
> final edit for LASD post

- content/2022_spring_tech_cluster_hire.md
> Add cluster hire post

- content/WDFN_tech_stack_spring_2022.md
> edits and publishing

- content/30daychartchallenge-2022.md
removing duplicate charts from chart challenge blog post
> thread posts appear duplicated

- content/snakemake-ml-experiments.md
@jkreft-usgs - can you merge so we can see if this title fits better? Also I made one image smaller b/c it was pretty huge in the previous preview.
> snakemake post: shorter title, smaller figure

- content/snakemake-ml-experiments.md
@jkreft-usgs - this is ready to go on my end
> Snakemake post change draft to "False"

- content/GWW.md
This is the updated .md file for the post
> Updated header info

- content/GWW.md
> Updated to not a draft

- content/GWW.md
> Added reference to NWISweb
